### ISSUE TITLE
Need help: my app's cache is not persisted

### ISSUE THREAD

**Issue by leedstyh** [apollographql/apollo-cache-persist#39]
Following is my code:

```
import React 	from "react"
import ReactDOM from "react-dom"

import ApolloClient, { gql } 	   from 'apollo-boost'
import { ApolloProvider, graphql } from 'react-apollo'

import { InMemoryCache } from 'apollo-cache-inmemory'
import { persistCache }  from 'apollo-cache-persist'

const q = gql`
	query {
		dog(breed: "bulldog") {
			id
			breed
			displayImage
		}
	}
`

const Main = graphql(q)(({data: { loading, error, dog }})=>{
	if (loading) return <p>Loading</p>
	if (error)   return <p>Error</p>

	return <p><img alt="" src={dog.displayImage} /></p>
})

const cache = new InMemoryCache()

persistCache({
	cache,
	storage: window.localStorage,
	debug: true,
}).then(() => {
	const client = new ApolloClient({
		uri: 'https://nx9zvp49q7.lp.gql.zone/graphql',
		cache
	})

	const App = () => (
		<ApolloProvider client={client}><Main /></ApolloProvider>
	)

	ReactDOM.render(<App />, document.getElementById("root"))
})

```

But I don't see anything in the localStorage in my browser (Chrome), am  missing something?

**Comment by jamesreggio** [comment]
Hi @leedstyh —

Can you check to see if you see a line that looks like this in your console?

```
[apollo-cache-persist] Persisted cache of size XXX
```

If so, the cache is working, and perhaps you're looking at the wrong `localStorage` instance.

If you don't see it, can you confirm that your query actually completed successfully? If your query doesn't receive data, there will be no data to cache.

**Comment by leedstyh** [comment]
Don't see that message, and yes the query is completed that I get the image displayed

**Comment by leedstyh** [comment]
Only see `[apollo-cache-persist] No stored cache to restore` every time I reload the page @jamesreggio

**Comment by leedstyh** [comment]
Wanna build and upload to netlify to show you a live demo, but when I `npm run build` (I use CRA) I got these error:

```
> apollo_test@0.1.0 build d:\code\reactjs\apollo_test
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-apollo/parser.mjs:13

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo_test@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo_test@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leeds\AppData\Roaming\npm-cache\_logs\2018-03-15T00_05_37_611Z-debug.log
```

the log file prints:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle apollo_test@0.1.0~prebuild: apollo_test@0.1.0
6 info lifecycle apollo_test@0.1.0~build: apollo_test@0.1.0
7 verbose lifecycle apollo_test@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle apollo_test@0.1.0~build: PATH: D:\node\node_modules\npm\bin\node-gyp-bin;d:\code\reactjs\apollo_test\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\node;D:\go\bin;C:\Program Files\Git\cmd;D:\flutter\bin;D:\flutter\bin\cache\dart-sdk\bin;D:\Android\Android Studio\jre\bin;D:\bin;d:\python;D:\Softwares\7-ZipPortable\App\7-Zip;C:\Users\leeds\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle apollo_test@0.1.0~build: CWD: d:\code\reactjs\apollo_test
10 silly lifecycle apollo_test@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle apollo_test@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle apollo_test@0.1.0~build: Failed to exec build script
13 verbose stack Error: apollo_test@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\node\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\node\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid apollo_test@0.1.0
15 verbose cwd d:\code\reactjs\apollo_test
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error apollo_test@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the apollo_test@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Not sure if this helps.

**Comment by duytq94** [comment]
I have the same problem, if I use "persistCache" it seem not persist the cache.
May be you can try to "CachePersistor" instead and manual handle when the cache is persist, when is restore.

**Comment by wtrocki** [comment]
> Then I try to "CachePersistor" instead and manual handle when the cache is persist, when is restore. And it work, the console is show "[apollo-cache-persist] Persisted cache of size XXX". But in don't know what XXX is the number for what infor, is it a Kb of data persist, or Mb, or something else.

Is length of the string if the content is a string. 
I made fix to make this clear. 
As far I see other issues were resolved. 
If not please reopen or create new issue.
